import type { Metadata } from "next";
import { Geist, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { TimelineProvider } from "@/context/TimeLineContext";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KeenKeeper",
  description: "Generated by rakib",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col pt-16 ">
        <Navbar />
        <TimelineProvider> {children}
          <ToastContainer position="top-center" /> 
        </TimelineProvider>
        <Footer/>
      </body>
    </html>
  );
}
